parameters:
#    tdp_front.example.class: Tdp\FrontBundle\Example

services:
#    tdp_front.example:
#        class: %tdp_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
